service: aws-node-express-api-project 
frameworkVersion: '2.72.4'

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1

  apiGateway:
    apiKeys:
      - myfirstapikey

functions:  
  api:
    handler: index.handler
    name: express-api-function
    events:
      - http:
          path: /hello
          method: GET
          private: true

